<?php

	$helper = $this->helper('Lof\MarketPlace\Helper\Data');
?>
<div class="page-title">
  <div class="title_left">
    <h3><?php echo __('Shipment'); ?></h3>
  </div>
</div>
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
	            <h2><?php echo __('Table Shipment'); ?></h2>
	            <div class="clearfix"></div>
	         </div>
	         <div class="x_content">
				<div class="table-responsive">
					<table id="datatable" class="table table-striped table-bordered">
						<thead>
	                      	<tr class="headings">
	                 			<th class="hidden"></th>
		                        <th class="column-title"><?php echo __('Shipment');?> </th>
		                        <th class="column-title"><?php echo __('Ship Date');?> </th>
		                        <th class="column-title"><?php echo __('Order #');?> </th>
		                        <th class="column-title"><?php echo __('Order Date');?> </th>
		                        <th class="column-title"><?php echo __('Ship to Name');?> </th>
	                            <th class="column-title"><?php echo __('Total Quantity');?> </th>
	                            <th class="column-title no-link last"><span class="nobr"><?php echo __('Action'); ?></span>
	                            </th>
	                            <th class="bulk-actions" colspan="7">
	                              <a class="antoo" style="color:#fff; font-weight:500;"><?php echo __('Bulk Actions');?> ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
	                            </th>
	                      	</tr>
	                    <tbody>
	                    <?php foreach ($this->getOrder()->setOrder('order_id', 'desc') as $key => $order) { 
	                    	$shipment = $this->getShipmentsByOrderId($order->getData('order_id'));
	                    	$order_data = $this->getOrderData($order->getData('order_id'));
	                    	if(count($shipment->getData()) > 0) {
	                    	?>
	    					<tr class="even pointer">
	    						<td class="hidden"></td>
	                            <td class=" "><?php echo $shipment->getData('increment_id'); ?></td>
	                            <td class=" "><?php echo $this->formatDate(
								    $this->getOrderAdminDate($shipment->getData('created_at')),
								    \IntlDateFormatter::MEDIUM,
								    true
								);?></td>
	                             <td class=" "><?php echo $order_data->getData('increment_id'); ?></td>
	                            <td class=" "><?php echo $this->formatDate(
								    $this->getOrderAdminDate($order_data->getData('created_at')),
								    \IntlDateFormatter::MEDIUM,
								    true
								);?></i></td>
	                            <td class=" "><?php $customer = $helper->getCustomerById($shipment->getData('customer_id')); 
	                            echo $customer->getFirstName().' '.$customer->getLastName(); ?></i></td>
	                            <td class=" "><?php echo $shipment->getData('total_qty'); ?></td>
	                            <td class=" last"><a href="<?php echo $block->getUrl('catalog/sales/shipmentview', ['view' => $shipment->getData('entity_id')]); ?>"><?php echo __('View'); ?></a>
			                </td>
	    					</tr>
	                    	<?php } 
	                	}?>  
	                    </tbody>      
					</table>
				</div>
			</div>
		</div>
	</div>
</div>