<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<script>
    window.sellerCollection = <?php echo json_encode($block->getSellerCollection());?>;
    window.methodTitle = '<?php echo $block->getMethodTitle();?>';
    window.carrierTitle = '<?php echo $block->getCarrierTitle();?>';
</script>
<style type="text/css">
    .item-product {
        margin-left: 20px;
    }
    .item-product span{
        margin-left: 30px;
    }
    .seller-rates {
        margin-left: 40px !important;
    }
    dt {
        border-bottom: 1px solid grey;
    }
    dd {
        padding: 5px;
    }
    .choice {
        padding: 10px;
        border-bottom: 1px solid grey;
    }
    .methods {
        padding: 5px;
        background-color: #f1f1f1;
    }
    #total-price {
        font-weight: bold;
    }
</style>
