<div id="cart-totals" class="cart-totals">
    <div class="table-wrapper">
        <table class="data table totals">
            <caption class="table-caption">Total</caption>
            <tbody>
            <tr class="totals sub">
                <th class="mark"><strong>Subtotal</strong></th>
                <td class="total amount">
                    <strong><span><?php echo $block->getCurrencySymbol() ?></span><span id="subtotals-value">0.00</span></strong>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>