<?php
$helper = $this->helper('Lof\MarketPlace\Helper\Data');
$formActionUrl = $this->getUrl('catalog/messageadmin/save');
$currPageUrl = $helper->getCurrentUrls();
$this->isRead();
 
?>
<div class="row">
  	<div class="col-md-6 col-sm-6 col-xs-12">
	    <div class="x_panel">
	      	<div class="x_title">
	        	<h2><?php echo $this->getMessage()->getSubject();?></h2>
	        <div class="clearfix"></div>
	    	</div>
		    <div class="x_content">
		    	<p><?php echo $this->getMessage()->getDescription();?></p>
		    </div>
		</div>    
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="x_panel">
    		<div class="x_title">
    			<h2><?php echo __('Post a Reply');?></h2>
    			<div class="clearfix"></div>
    		</div>
    		<div class="x_content">
	    		<form id="form-message" data-parsley-validate="" action="<?php echo $formActionUrl;?>" class="form-horizontal form-label-left" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
	                <div class="form-group">
	                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="content"><?php echo __('Message');?> <span class="required">*</span>
	                    </label>
	                    <div class="col-md-6 col-sm-6 col-xs-12">
	                      <textarea name="content" rows="10" id="content" required="required" class="form-control col-md-7 col-xs-12"> </textarea>
	                    </div>
	                </div>
	                <div class="ln_solid"></div>
	                <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        	<input type="hidden" name="sender_id" value="<?php echo $this->getSeller()->getSellerId();?>" />
                        	<input type="hidden" name="seller_send" value="1" />
                        	<input type="hidden" name="sender_name" value="<?php echo $this->getSeller()->getName();?>" />
                        	<input type="hidden" name="sender_email" value="<?php echo $this->getSeller()->getEmail();?>" />
                        	<input type="hidden" name="message_id" value="<?php echo $this->getMessage()->getMessageId();?>" />
                        	<input type="hidden" name="currUrl"  id="currUrl" value="<?php echo $currPageUrl; ?>" />
						  	<button class="btn btn-primary" type="reset"><?php echo __('Reset');?></button>
                          	<button type="submit" class="btn btn-success"><?php echo __('Submit');?></button>
                        </div>
                    </div>
	            </form>
	    	</div>
    	</div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="x_panel">
    		<div class="x_title">
    			<h2><?php echo __('Message History');?></h2>
    			<div class="clearfix"></div>
    		</div>
    		<div  class="x_content" >
    			<ul class="messages">
    				<?php foreach ($this->getDetail() as $key => $detail) { ?>
    				<li>
	                    <div class="message_date">
	                      	<h4 class="date text-info"><?php echo $helper->nicetime($detail->getCreatedAt());?></h4>
	                      	<p class="month"><?php echo $helper->getFormatDate($detail->getCreatedAt()); ?></p>
	                    </div>
	                    <div class="message_wrapper">
	                      	<h4 class="heading"><?php echo $detail->getSenderName();?></h4>
	                      	<blockquote class="contact-message"><?php echo $detail->getContent(); ?></blockquote>
	                    </div>
                  	</li>
    				<?php } ?>
                </ul>
    		</div>
    	</div>
    </div>
</div>