<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Gdpr
 */
?>
<?php /** @var \Amasty\Gdpr\Block\Popup $block */ ?>

<div class="amgdpr-privacy-policy" id="amgdpr-privacy-popup">
</div>

<script type="text/x-magento-init">
    {
        "#amgdpr-privacy-popup": {
            "Amasty_Gdpr/js/popup":{
                "title":"<?= $block->escapeHtml(__('Privacy Policy')); ?>",
                "textUrl":"<?= $block->escapeUrl($block->getTextUrl()); ?>"
            }
        }
    }
</script>
